# -*- coding: utf-8 -*-
"""Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q6dxUzuXjlOhXlM4Cdu2f_FAEzymCVS6
"""

import pandas as pd # BAnco de dados
import statsmodels.formula.api as sms # Regressão
import matplotlib.pyplot as plt # Visualização
import numpy as np # Biblioteca numérica do python
# %matplotlib inline

# Lendo os dados da web

adv = pd.DataFrame.from_csv("http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv")
adv.head() # a variável dependente são as vendas

# Tirando estatísticas descritivas
adv.describe()

# Verificar as dimensões do banco
adv.shape

# Outra forma
r,c = adv.shape
print("O banco de dados possui {} linhas e {} colunas".format(r,c) )

# Verificando a distribuição da variável resposta
plt.hist(x=adv['sales'])
plt.title("Histograma de Sales")
plt.ylabel("Frequência")
plt.show()

# Verificar a distribuição da variável TV com um histograma
plt.hist(x=adv["TV"], color="pink")
plt.title("Histograma de investimento em TV")
plt.ylabel("Frequência")
plt.show

# Verificar a distribuição da variável Rádio com um histograma
plt.hist(x=adv["radio"], color= "violet")
plt. title("Histograma de investimento em Rádio")
plt.ylabel("Frequência")
plt.show

# Plotar um gráfico identificando a relação entre investimento em TV e retorno em vendas
plt.scatter(x=adv["TV"], y=adv["sales"], color= "purple")
plt.ylabel("Sales")
plt.xlabel("Investimentos em TV")
plt.show

# Montando o modelo de regressão
model = sms.ols(formula="sales ~ TV", data=adv).fit() # Estimar modelo
print(model.summary())